language: node_js
node_js:
  - '12'

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      script:
        - yarn eslint '*/**/*.{js,ts}' --quiet
        # - commitlint-travis
        - yarn test
        - yarn test:integration
        - yarn add --dev codecov
        - yarn codecov

    - stage: deploy
      script:
        - yarn build
        - yarn build:doc
        - yarn semantic-release
        - yarn deploy:doc

cache: yarn
